version: '3.4'
services:
  app:
    environment:
      PORT: '3000'
    build:
      context: ./
      target: development
    entrypoint: bash -c "npm install && npm run dev"
    ports:
      - '4000:3000'
    volumes:
      - './:/app'